### ISSUE TITLE
Feature Request: Add SEP-12 support 

### ISSUE THREAD

**Issue by shanzzam** [stellar/stellar-demo-wallet#103]
### What problem does your feature solve?
Given the challenges some wallet developers have encountered implementing SEP-12, creating our own end-to-end test integration would help us see where the pain points are and provide developers insight as they developer their own solutions.

### What would you like to see?
Provide a way for wallet developers to test wallet implementation against anchor test servers or aPolaris test server. 

### What alternatives are there?
None at the moment. If SEP-12 isn't used very much, or is not a priority SEP for use, perhaps we don't need this feature.

**Comment by JakeUrban** [comment]
I think we'll have good examples of how SEP-12 will work by implementing SEP-31 (already done) and SEP-6. @shanzzam I'm going to close this issue, but let me know if you think we should build a standalone SEP-12 flow in the demo wallet.
