### ISSUE TITLE
The SEP-8 approval server should be able to revise transaction payments for the happy path

### ISSUE THREAD

**Issue by marcelosalloum** [stellar/stellar-demo-wallet#120]
### Summary

The [SEP-8] approval server should be able to receive a transaction and sandwich its **payments** with `AllowTrust` operations.

At first we should focus on landing a code that addresses the **happy path**, i.e. if the incoming transaction contains only one operation of the type "payment" whose asset is issued by the issuing account we should [revise the transaction](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0008.md#transaction-composition), going from:
```sh
Operation 1: Payment from A to B
```

into:
```sh
Operation 1: AllowTrust op where issuer fully authorizes account A, asset X
Operation 2: AllowTrust op where issuer fully authorizes account B, asset X
Operation 3: Payment from A to B
Operation 4: AllowTrust op where issuer fully deauthorizes account B, asset X
Operation 5: AllowTrust op where issuer fully deauthorizes account A, asset X
```

### Request

According with SEP-8 the [request format](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0008.md#post-endpoint) expected by the approval server should look like:
#### `POST /tx_approve`

**Request:**
```javascript
{
  "tx": "AAAAAHAHhQtYBh5F2zA6..." // the transaction XDR
}
```

**Response:**
```javascript
{
  "status": "revised",
  "tx": "AAAAAHAHhQtYBh5F2zA6...",
  "message": "Authorization and deauthorization operations were added."
}
```

For more info please refer to https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0008.md#revised

### Toml File

We should update the toml file [approval_criteria] explaining the approval server only supports payment operations.

[SEP-8]: https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0008.md
[approval_criteria]: https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0008.md#example

**Comment by marcelosalloum** [comment]
It'd be nice if the logic to approve/revise a transaction was inside its own method, so our approval server reference implementation can be easily reused by third parties by replacing this one method.

**Comment by marcelosalloum** [comment]
Why is this issue being closed? We haven't landed that yet, have we?

**Comment by Zagan202** [comment]
> Why is this issue being closed? We haven't landed that yet, have we?

Whoops I misclicked somehow
