### ISSUE TITLE
SEP-31 support all possible statuses

### ISSUE THREAD

**Issue by shanzzam** [stellar/stellar-demo-wallet#146]
@quietbits commented on [Mon Mar 22 2021](https://github.com/stellar/nebula/issues/159)

Currently, we're handling only the "happy path". [Documentation](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0031.md#pending-customer-info-update) for all possible statuses.

**Comment by JakeUrban** [comment]
We did this with #147 !
