### ISSUE TITLE
UI for SEP-08 Send Asset flow

### ISSUE THREAD

**Issue by shanzzam** [stellar/stellar-demo-wallet#152]
Screens and UI flow for the following:

- [x] Start or Cancel SEND action
- [x] SEND action
- [x] Handle additional information required from Server (build client forms dynamically)
- [x] Handle addition information response
- [x] User review for revised transaction (Cancel or Send)
- [x] Handle transaction send response (success or fail)

**Comment by marcelosalloum** [comment]
This should be complete by now. Please let me know if you think there's something missing.
