### ISSUE TITLE
Support the ability to send to muxed accounts

### ISSUE THREAD

**Issue by shanzzam** [stellar/stellar-demo-wallet#156]
### What problem does your feature solve?
Muxed account support has existed as of Protocol 13 and the SEP defining "M" strkeys are in [draft](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0023.md). We've recently added support to our SDKs ([GO](https://github.com/stellar/go/issues/3543) and [JS](https://github.com/stellar/js-stellar-base/pull/416)) to opt-in to use of muxed accounts with M addresses. To roll out support, we'll be implementing this in our developer tools.  

### What would you like to see?
Add support to Send to M-addresses in an on-chain transaction.

**Comment by shanzzam** [comment]
@shanzzam and @lydiat Still need to review and test this

**Comment by piyalbasu** [comment]
This can be tested on the Release/1.2.0 PR:
http://stellar-demo-wallet-pr177.previews.kube001.services.stellar-ops.com/

**Comment by shanzzam** [comment]
This has been tested and will be in the next demo wallet release. 1.2
