### ISSUE TITLE
Display error messages for unexpected anchor responses

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-demo-wallet#169]
As originally discussed in [this issue](https://github.com/stellar/django-polaris/issues/426), the demo wallet does not render a helpful error message to the user when the anchor returns an unexpected error response. Whenever the demo makes a request to the anchor, it should handle unexpected responses by notifying the user instead of silently failing.

**Comment by quietbits** [comment]
In this case, it looks like this was a bug with customer types in SEP-31 send. We don't need to update error messages to fix it.
