### ISSUE TITLE
Getting CORS error for localhost anchors

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-demo-wallet#178]
I'm unable to add an asset using a localhost domain. I can see the following error in the console logs:

> Access to XMLHttpRequest at 'http://localhost:8000/.well-known/stellar.toml' from origin 'https://demo-wallet.stellar.org' has been blocked by CORS policy: Request header field sentry-trace is not allowed by Access-Control-Allow-Headers in preflight response.

Seems like Sentry is trying to add a request header to a CORS request and its getting blocked. The CORS configuration on my local server is the same as the configuration used in the testanchor.stellar.org deployment though, so I don't understand why we're having this issue. @quietbits do you have any ideas?

**Comment by leighmcculloch** [comment]
CORS is unsupported on some browsers, namely Chrome. https://stackoverflow.com/questions/10883211/why-does-my-http-localhost-cors-origin-not-work

**Comment by quietbits** [comment]
@JakeUrban It seems to be working for me. I just tried my local toml file (which is the exact copy of testanchor.stellar.org) on demo-wallet.stellar.org, it worked just fine (with and without ad blocker). Which browser are you trying? I tried Chrome on Windows.

![image](https://user-images.githubusercontent.com/7346473/120656118-57d67680-c451-11eb-99bb-19040374cb16.png)

**Comment by JakeUrban** [comment]
@quietbits I'm running chrome on macOS. @leighmcculloch is there a reason you hid your comment? A Polaris user also confirmed they were unable to get the demo wallet to connect to the HTTP local Polaris server.

**Comment by shanzzam** [comment]
@quietbits putting this on the backlog to look at in sprint planning tomorrow.

**Comment by JakeUrban** [comment]
@quietbits I'm getting the same sentry-trace error again, and I see there have been a couple changes to the related code in App.tsx, although I'm not sure what the problem is because it seems the configuration was moved to a different package.

**Comment by shanzzam** [comment]
Putting this in the current sprint as it was reset to the "In Review" pipeline when it was reopened.

**Comment by piyalbasu** [comment]
Fixed by https://github.com/stellar/stellar-demo-wallet/releases/tag/v1.2.2
