### ISSUE TITLE
Balance amounts are overwritten to 0

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-demo-wallet#196]
We were on a call with a partner who was using the demo wallet to test their local anchor and had two asset balances, one from a non-local anchor and another from a localhost anchor.

When the partner loaded an account with non-zero balances, it momentarily showed the real balances but both balances were quickly updated to 0. I'm not sure what the technical reasons for this would be but the partner mentioned that he noticed the bug about a week ago.

**Comment by shanzzam** [comment]
Fixed with https://github.com/stellar/stellar-demo-wallet/issues/188 and is active in the [1.2 branch](https://github.com/stellar/stellar-demo-wallet/tree/release/1.2.0). Please confirm there if possible.

**Comment by JakeUrban** [comment]
Hi @marcelosalloum can I close this issue?

**Comment by marcelosalloum** [comment]
Yes, it should e fixed by now.
