### ISSUE TITLE
SEP-8 deposit failed when running sep-6, deposit

### ISSUE THREAD

**Issue by lijamie98** [stellar/stellar-demo-wallet#236]
### What version are you using?
The current version at https://demo-wallet.stellar.org. Cannot find the version string from the site.

### What did you do?

1. Create an account. 
2. Added SRT
3. Run "SEP-6 Deposit" Action on SRT
4. Enter amount 1000
5. Leave Bank Account Number and Routing Number blank
6. In the following screen, click "Proceed"
![image](https://user-images.githubusercontent.com/7027284/131407605-700648cd-ce7e-4350-96b8-65ccfa409a55.png)
7. SEP-8 deposit failed. 
![image](https://user-images.githubusercontent.com/7027284/131407755-6d1157ad-62ed-4313-a17a-369ef3f4da39.png)

### What did you expect to see?
Success

### What did you see instead?
Sep-8 deposit failed

**Comment by quietbits** [comment]
The issue here is that the account is not created/funded (no XLM to fund the transaction). We could improve messaging around it to make it more clear.

The typo "SEP-8 deposit failed" (should say "SEP-6 deposit failed") is fixed in https://github.com/stellar/stellar-demo-wallet/pull/239.
