### ISSUE TITLE
Add show/hide functionality to JSON in logs

### ISSUE THREAD

**Issue by lydiat** [stellar/stellar-demo-wallet#24]
The [SEP24 Demo Client ](https://github.com/stellar/sep24-demo-client ) uses a show/hide link to keep the JSON shown in logs neat - we need to port this over to the Stellar demo wallet.

![Screen Shot 2020-07-15 at 1 37 11 PM](https://user-images.githubusercontent.com/1917909/87593707-bb707d80-c6a0-11ea-8579-43450c35257e.png)

**Comment by msfeldstein** [comment]
We use the [`renderjson`](https://www.npmjs.com/package/renderjson) package for this in the demo client, should work fine here too.

```
const Renderjson = require("renderjson");
Renderjson.set_show_to_level(1);
div.appendChild(Renderjson(params));
```

https://github.com/stellar/sep24-demo-client/blob/master/src/ui/ui-actions.js#L110

**Comment by JakeUrban** [comment]
Looks like this actually already happened.
