### ISSUE TITLE
Cannot connect to localhost on Safari

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-demo-wallet#249]
If you're using Safari, you cannot connect to `localhost` anchors. Errors below:

<img width="745" alt="Screen Shot 2021-10-24 at 4 25 07 PM" src="https://user-images.githubusercontent.com/10968980/138617125-0bc3d33d-3840-45d5-a811-8a374a3f0662.png">
<img width="577" alt="Screen Shot 2021-10-24 at 4 25 20 PM" src="https://user-images.githubusercontent.com/10968980/138617126-52dd9791-5b47-4b48-abc3-ac1ba0d7aca0.png">

@quietbits do you know what could be causing this?

**Comment by quietbits** [comment]
It looks like this is a restriction in the Safari browser. A note was added about it in the readme (#250).
