### ISSUE TITLE
Feature Request: implement sep10 client attribution

### ISSUE THREAD

**Issue by tomerweller** [stellar/stellar-demo-wallet#251]
Some anchors require interacting wallets to implement [SEP10 Client Attribution](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0010.md#verifying-the-client-domain). Right now, these anchors can't use the demo wallet as it does not support this feature.

**Comment by stfung77** [comment]
added a backend server to sign requests for sep10 client attribution in PR 255
