### ISSUE TITLE
Notify the user when using the demo wallet on mainnet

### ISSUE THREAD

**Issue by brunomuler** [stellar/stellar-demo-wallet#291]
Since the demo wallet is intended to be used as a test tool and the secret key handling security is not a focus, we could let users to know about this when using it on mainnnet just to be extra safe.

Two changes would make this possible:
1. Replace the label in the checkbox that now says `Operate on pubnet (NOT RECOMMENDED)` with  `Operate on mainnet. ATTENTION: use this as a test tool only. Consider any secret key used with the Demo Wallet as compromised.`
<img width="699" alt="Screen Shot 2022-08-02 at 1 47 21 PM" src="https://user-images.githubusercontent.com/1879192/182471022-e5e271cb-05f0-4e08-a77f-33b29fe23596.png">

2. If the mainnet is being used, include a fixed banner on top with the copy `The Demo Wallet is intended to be used as a test tool only. Consider any secret key used with the Demo Wallet as compromised.`

**Comment by C0x41lch0x41** [comment]
Thanks a lot @brunomuler 
This approach looks good to me!

**Comment by brunomuler** [comment]
We're replacing this change to a [more secure approach](https://github.com/stellar/stellar-demo-wallet/issues/292)
