### ISSUE TITLE
Add SEP31 support

### ISSUE THREAD

**Issue by abuiles** [stellar/stellar-demo-wallet#31]
### What problem does your feature solve?

Adds a SEP31 demo.

### What would you like to see?

A button "Send to Bank" which makes a transfer to a bank account via SEP31 using the testanchor.

### What alternatives are there?

- https://sep31-demo-client.netlify.app/

**Comment by shanzzam** [comment]
This is currently being done as part of the overhaul of all Demo Clients into one application.

**Comment by JakeUrban** [comment]
Done!
