### ISSUE TITLE
SEP-24 deposit in progress pulls transaction update for few seconds then ends with error of `Failed to fetch`

### ISSUE THREAD

**Issue by gabrieladeniji** [stellar/stellar-demo-wallet#367]
### What version are you using?
I should be using the latest version, as I'm accessing the demo wallet from this URL (https://demo-wallet.stellar.org)

### What did you do?
Testing (SEP-24) as an anchor `https://anchorsb.paychant.com/.well-known/stellar.toml`

### What did you expect to see?
Once the transaction has been initiated, then the start button was clicked from the "SEP-24 Deposit" modal, the "SEP-24 deposit in progress" should still be active (checking the transaction by pulling for update), until the opened URL window closes or the transaction failed/completed.

<img width="840" alt="Screenshot 2024-09-17 at 8 20 46 AM" src="https://github.com/user-attachments/assets/681d4ef0-185a-4f29-b600-9343306eec77">

### What did you see instead?
Instead the "SEP-24 deposit in progress" display for a few seconds (checking the transaction by pulling for an update for a few seconds), then it stopped with the error of `Failed to fetch` while the opened URL window was still active.

<img width="1161" alt="Screenshot 2024-09-16 at 2 47 59 PM" src="https://github.com/user-attachments/assets/c3341218-f06c-4266-adb8-098097a40856">

<img width="611" alt="Screenshot 2024-09-16 at 2 50 25 PM" src="https://github.com/user-attachments/assets/87c0bbc1-1923-4070-b79f-35b11d092967">

**Comment by quietbits** [comment]
@gabrieladeniji, thank you for reporting this. I couldn't reproduce this by doing a basic SEP-24 deposit (no custodial mode and no SEP-9 fields selected). Does it work for you with [this account](https://demo-wallet.stellar.org/account?secretKey=SAXFPM4OEJWZ6JIQWTWKHZPLH63WA6DN3J4CLSNCUXHFSJ2DHKZVF3FK&assetOverrides=USDC%3AGBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5%7ChomeDomain%3Ehttps%3A%2F%2Fanchorsb.paychant.com%2F)?

Any extra information you can provide will help us figure out what is wrong here. I'm not sure why the `https://anchorsb.paychant.com/sep24/transaction` would be blocked for you. It was still OK for me with an ad block in Chrome.

![image](https://github.com/user-attachments/assets/2c995133-9b24-4f21-82a6-c7624e6a42f4)

**Comment by gabrieladeniji** [comment]
Yes, it works for me now [account](https://demo-wallet.stellar.org/account?secretKey=SAXFPM4OEJWZ6JIQWTWKHZPLH63WA6DN3J4CLSNCUXHFSJ2DHKZVF3FK&assetOverrides=USDC%3AGBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5%7ChomeDomain%3Ehttps%3A%2F%2Fanchorsb.paychant.com%2F)

I think the issue was with my Chrome browser calling for an update, as soon as I finished updating it, everything started working properly (no more pulling for an update for a few seconds again)

thanks @quietbits
