### ISSUE TITLE
Add SEP-6 Support

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-demo-wallet#40]

**Comment by shanzzam** [comment]
- [ ] Detect SEP-06 supported assets and display Asset UI accordingly (deposit and withdraw)
- [ ] Support the use case where a trustline doesn't exist using claimable balances 
- [ ]  Support the use case where more customer information is needed (non_interactive_customer_info_needed)

**Comment by shanzzam** [comment]
@piyalbasu will you link the PRs to this issue please.

**Comment by piyalbasu** [comment]
Ah yes, sorry - it can be reviewed on the Release/1.2.0 PR: 
http://stellar-demo-wallet-pr177.previews.kube001.services.stellar-ops.com/

**Comment by shanzzam** [comment]
This has been reviewed and is ready for release.
