### ISSUE TITLE
Deleted all the branches!

### ISSUE THREAD

**Issue by tyvdh** [stellar/stellar-demo-wallet#50]
There were a bunch of branches that our Build Apps tutorial was pointing to. 
Why were they removed and please add them back ASAP!!!

https://developers.stellar.org/docs/building-apps/

This repo isn't just a reference implementation, it was first and still is a tutorial resource.

Might be worth splitting it but until we've done that please keep the branches that the tutorial is pointing to.

cc: 
@JakeUrban 
@Zagan202 
@lydiat

**Comment by Zagan202** [comment]
Currently restoring now.
Apologies, we can discuss a path forward for maybe splitting the repo
or
Make tags on Master and have the docs point to specific versions (like `setup` etc.) to keep the "stale branches" to a minimum.

**Comment by leighmcculloch** [comment]
Moving forward we should do one of the following if these branches are important:
- Use GitHub's protected branch feature to prevent pushes to the branches or deletes.
- Use tags instead of branches since they're harder to delete via the UI.

**Comment by leighmcculloch** [comment]
If it is possible for us to change the name of the branches referenced in the docs it might be worth us prefixing them with a common name like `tutorial-` so it is a bit clearer what they are too.

**Comment by shanzzam** [comment]
Updating the README with this use of branches would be helpful as well. Coming it to this as an outside/new developer, I wouldn't expect to use branches in this way.

**Comment by tyvdh** [comment]
Agree with all of the points here. After Meridian let's regroup and come up with our game plan for this repo. I don't think I've ever really used tags but I like the sound of that idea.

**Comment by JakeUrban** [comment]
We'll keep the branches as-is, sorry for deleting them. Just want to confirm that @Zagan202 and I are free to change `master` as we see fit, is that alright?

**Comment by tyvdh** [comment]
That's correct. Sorry for the confusion and lack of clarity around the other branches. The repo kinda took on a life of it's own after I created it for the tutorial. 😆

**Comment by JakeUrban** [comment]
Thats the price of creating something valuable!
