### ISSUE TITLE
Feature Request: Add `Send ClaimableBalance` to Destination Account

### ISSUE THREAD

**Issue by Zagan202** [stellar/stellar-demo-wallet#51]
### What problem does your feature solve?

Give Accounts the access to send a claimable balance to other accounts

### What would you like to see?

Alongside the the `Send` `Deposit` and `Withdraw` buttons under the asset's balance include a `send claimable balance` button.

The UI will look nearly identical to the send feature.

**Comment by JakeUrban** [comment]
Maybe we should send a claimable balance if the destination account doesn't have a trust-line, but do it automatically without a separate button? We could have the right-side logs show that a claimable balance was sent.

**Comment by JakeUrban** [comment]
This is no longer needed because we have #54
