### ISSUE TITLE
Add Mainnet Support

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-demo-wallet#53]
The old demo client can run everything on mainnet, we should offer the same functionality on the demo wallet.

This should simply involve making the `NETWORK_PASSPHRASE` used configurable, with some kind of toggle button for switching between testnet and mainnet.

The only challenge I see with this issue is this project's use of Friendbot for `createAccount()`. We may have to remove the `Create Account` button if mainnet is selected.

**Comment by leighmcculloch** [comment]
➕ 1️⃣  although we should refer to it as Pubnet, as that's what the public Stellar network is called in other tools and documentation.

**Comment by JakeUrban** [comment]
Oh thats good to know, we definitely call it mainnet in all our integration resources sent to partners. I always assumed the two words could be used interchangeably. I almost prefer 'mainnet' because 'pubnet' implies the other network would be 'privatenet'

**Comment by leighmcculloch** [comment]
I don't have a personal preference other then we should be consistent and it's not worth changing. Most public documentation, tools, and SDKs use the term testnet/pubnet or test/public.

Examples:

- https://www.stellar.org/developers/guides/concepts/networks.html#network-passphrases
   >Pubnet: `'Public Global Stellar Network ; September 2015'`
   >Testnet: `'Test SDF Network ; September 2015'`

- https://stellar.github.io/js-stellar-sdk/global.html#Networks

- https://stellar.expert/explorer/public
