### ISSUE TITLE
Feature Request: Extend `Send` method to send a claimable balance if destination has no trust-line

### ISSUE THREAD

**Issue by Zagan202** [stellar/stellar-demo-wallet#54]
### What problem does your feature solve?

Doesn't block source account from sending an asset to a destination account that doesn't have a trust-line established for that asset. 

### What would you like to see?

When the source account attempts a send (`make payment`) operation to a destination account that doesn't have a trust line established for that asset it should instead attempt a claimable balance operation for that account.

**Comment by JakeUrban** [comment]
I think this issue is still relevant, but the user must have a method of specifying that making claimable balances is acceptable. We wouldn't want the payment to be sent to an account controlled by an application that doesn't support CB's.
