### ISSUE TITLE
Replace TESTNET and MAINNET raw strings with constants

### ISSUE THREAD

**Issue by Zagan202** [stellar/stellar-demo-wallet#56]
`'https://horizon-testnet.stellar.org'` `'https://horizon.stellar.org'`
should be replaced with global constants `TESTNET_URI` and `MANNET_URI`.

**Comment by leighmcculloch** [comment]
Can we use the term `PUBNET_URI`? For why see #53.

**Comment by abuiles** [comment]
@Zagan202 what about taking an ENV variable? That way it isn't bounded to our horizon instances.

**Comment by JakeUrban** [comment]
@Zagan202 it should default to our horizon instances for ease-of-use, but we could allow users to specify a different horizon URL via the environment. However, I think the vast majority of users will not be running this locally, and will just be using demo-wallet.stellar.org.
