### ISSUE TITLE
Feature Request: Tutorial Wallet vs Demo Wallet

### ISSUE THREAD

**Issue by tyvdh** [stellar/stellar-demo-wallet#68]
Hi friends, just opening a thread here to discuss the issue and resolution with where this wallet started and where it is now.

Originally this repo was created as a companion repo for the "Building Apps" tutorial: https://developers.stellar.org/docs/building-apps

Since then it has been adapted and utilized for far more than that however those tutorials all still point to this repo along with several other external articles and references.

Both use cases are obviously viable and necessary however considering the public nature of the tutorial my recommendation is to clone this repo into a new project and rename this repo `stellar-reference-wallet` and keep the `stellar-demo-wallet` name for the cloned tutorial wallet. This will allow all the links to not be broken (I hope) while keeping all the history, tickets, etc on this repo under a new name.

Thoughts?

cc: @JakeUrban @lydiat @Zagan202 @leighmcculloch

**Comment by tyvdh** [comment]
https://github.com/stellar/stellar-demo-wallet/issues/50

**Comment by JakeUrban** [comment]
Hi @tyvdh I'm not particularly opposed to doing something similar to what you suggest, but this app is currently deployed to demo-wallet.stellar.org

Its also not supposed to be a reference wallet -- its really a testing/debug tool for testing backend anchor services. For example, this wallet puts secret keys in it's URLs. We would never want a wallet to fork this repo to start their project because of this and other security-related reasons.

It seems more like your original project fits the "reference" name more accurately since it's supposed to act as a reference/starting-point for building a wallet right?

**Comment by tyvdh** [comment]
Hmm yeah I definitely hear that, though demo wallet still makes sense for the tutorial and changing all the links isn't really an option I don't feel, particularly as resources external to us are pointing here.

Or maybe we just include a callout in the README that redirects people if they're looking for the tutorial wallet.

**Comment by JakeUrban** [comment]
I like the README idea. But its not like these links in the documentation are immutable, it might be more helpful for people reading the tutorial to have links directly to the branch that is relevant to them.

**Comment by tyvdh** [comment]
Correct. On our side we can edit everything, I'm more concerned with external links pointing to this repo outside our control.

**Comment by JakeUrban** [comment]
Ok, I hear that. Can you make a PR that updates the README with a section that outlines the different branches you have and communicates that this project was adapted to serve a functional purpose (demo-wallet.stellar.org)?

**Comment by tyvdh** [comment]
Perfect. Have slotted a todo item for this for the next couple weeks. Thanks! Will close this ticket once this is finished.

**Comment by tyvdh** [comment]
The original docs/demo/tutorial wallet has a new home! https://github.com/stellar/docs-wallet. You may now do as you see fit with this repo. It's all yours! 

cc: @JakeUrban @quietbits
