### ISSUE TITLE
Make Demo Wallet more portable

### ISSUE THREAD

**Issue by Zagan202** [stellar/stellar-demo-wallet#70]
Currently its not easy to "linkify" and send others SEP scenarios
We need new query params to make this possible

Some ideas for query params
- "asset_code"
-  "domain"
-  "add_trust"
-  "CB" or "ClaimableBalance"

**Comment by Zagan202** [comment]
Also add untrusted assets to the account's url.
- We should ensure they're in sync with the balances saved to storage. 
- If asset is trusted then remove from untrusted section of the url.

**Comment by JakeUrban** [comment]
As it stands to day, only the untrusted assets information needs to be added to the URL. The only other parameter that needs to be in the URL has already been added: secret key.

**Comment by JakeUrban** [comment]
Closing because the demo wallet is portable as it stands today -- account state can be completely replicated by URL
