### ISSUE TITLE
Refactor Wallet's account attribute

### ISSUE THREAD

**Issue by Zagan202** [stellar/stellar-demo-wallet#74]
- rename  StellarAccount interface to AccountState
- rename  Balance interface to Asset
    - Pull the properties below into "Asset"

    ```json
    homeDomain?: string
    toml?: any
    ```

    - Deprecate interface WalletAssetDetails, @ Prop() assets @ Prop() balance

        ```json
        // export interface WalletAssetDetails {
        //   homeDomain?: string
        //   toml?: any
        // }
        ...
        // @Prop() assets: Map<string, WalletAssetDetails> = new Map()
        // @Prop() balance: Map<string, Balance> = new Map()
        ```

- Update AccountState interface to include `assets: Map<string, Asset>`

    ```json
    interface AccountState {
      publicKey: string
      secretKey: string
      response?: ServerApi.AccountRecord
      claimableBalances?: ServerApi.ClaimableBalanceRecord[]
      assets: Map<string, Asset>
    }
    ```

- Rename Asset interface's state property to `response`

    ```json
    interface AccountState {
      ...
      response?: ServerApi.AccountRecord
    ```

- Refactor code leverage the AccountState
    - Code that calls(writes or reads) the wallet obj's assets `prop` or `balance` will instead call AccountState.Asset
- Ensure we're saving wallet's AccountState to local storage.
- Deprecate balance keystore

**Comment by shanzzam** [comment]
Won't be doing in our refactor.
