### ISSUE TITLE
Remove "regulated asset" code

### ISSUE THREAD

**Issue by Zagan202** [stellar/stellar-demo-wallet#75]
Rip out any code that currently makes the way regulated assets work on the wallet.

**Comment by leighmcculloch** [comment]
Do we plan to maintain regulated asset functionality in the demo wallet? It would be useful to support SEP-8. cc @howardtw @shanzzam

**Comment by howardtw** [comment]
Yes we do. However, we plan on adding the SEP-8 support to the wallet sdk and have the demo wallet use the sdk.

**Comment by JakeUrban** [comment]
Closing because we removed the old regulated assets code from the application. It did not work anyway. After the refactor, adding SEP-8 functionality to the demo wallet can be a new issue.
